# Generated by Django 4.1.7 on 2023-03-26 06:27

from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slm', 'load_satellitesystems'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataavailability',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='dataavailability',
            index_together={('site', 'rinex_version', 'rate')},
        ),
        migrations.AddField(
            model_name='agency',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='last',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='rate',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Hourly'), (3, 'High Rate')], db_index=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='rinex_version',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(2, 'RINEX 2'), (3, 'RINEX 3'), (4, 'RINEX 4'), (211, 'RINEX 2.11'), (300, 'RINEX 3.00'), (301, 'RINEX 3.01'), (302, 'RINEX 3.02'), (303, 'RINEX 3.03'), (304, 'RINEX 3.04'), (305, 'RINEX 3.05'), (400, 'RINEX 4.00')], db_index=True, default=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dataavailability',
            unique_together={('site', 'rinex_version', 'rate', 'last')},
        ),
        migrations.AlterIndexTogether(
            name='dataavailability',
            index_together={('site', 'rinex_version', 'rate', 'last'), ('site', 'last'), ('site', 'rinex_version', 'last'), ('site', 'rinex_version'), ('site', 'rinex_version', 'rate')},
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ftp', models.URLField(max_length=255, unique=True)),
                ('ftp_user', models.CharField(blank=True, max_length=255)),
                ('ftp_password', models.CharField(blank=True, max_length=255)),
                ('ftp_root', models.CharField(blank=True, max_length=255)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slm.agency')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='dataavailability',
            name='data_centers',
            field=models.ManyToManyField(blank=True, to='slm.datacenter'),
        ),
    ]
