# Generated by Django 3.2.15 on 2022-10-02 17:15

from django.db import migrations, models
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='public',
            field=models.BooleanField(blank=True, default=True, help_text='Set to false to exclude all sites affiliated with this agency from public exposure.'),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='rinex_version',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(2, 'RINEX 2'), (3, 'RINEX 3'), (4, 'RINEX 4'), (211, 'RINEX 2.11'), (300, 'RINEX 3.00'), (301, 'RINEX 3.01'), (302, 'RINEX 3.02'), (303, 'RINEX 3.03'), (304, 'RINEX 3.04'), (305, 'RINEX 3.05'), (400, 'RINEX 4.00')]),
        ),
        migrations.AlterIndexTogether(
            name='siteform',
            index_together={('site', 'edited'), ('site', 'edited', 'published'), ('edited', 'published')},
        ),
        migrations.AlterIndexTogether(
            name='siteidentification',
            index_together={('site', 'edited'), ('site', 'edited', 'published'), ('edited', 'published')},
        ),
        migrations.AlterIndexTogether(
            name='sitelocation',
            index_together={('site', 'edited'), ('site', 'edited', 'published'), ('edited', 'published')},
        ),
        migrations.AlterIndexTogether(
            name='sitemoreinformation',
            index_together={('site', 'edited'), ('site', 'edited', 'published'), ('edited', 'published')},
        ),
    ]
