# Generated by Django 4.1.5 on 2023-02-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0001_alter_site_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteantenna',
            name='installed',
            field=models.DateTimeField(help_text='Enter the date the receiver was installed. Format: (CCYY-MM-DDThh:mmZ)', verbose_name='Date Installed (UTC)'),
        ),
        migrations.AlterField(
            model_name='siteantenna',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, help_text='Enter the date the receiver was removed. It is important that the date removed is entered before the addition of a new receiver. Format: (CCYY-MM-DDThh:mmZ)', null=True, verbose_name='Date Removed (UTC)'),
        ),
        migrations.AlterField(
            model_name='siteidentification',
            name='date_installed',
            field=models.DateTimeField(help_text='Enter the original date that this site was included in the IGS. Format: (CCYY-MM-DDThh:mmZ)', null=True, verbose_name='Date Installed (UTC)'),
        ),
        migrations.AlterField(
            model_name='sitereceiver',
            name='installed',
            field=models.DateTimeField(help_text='Enter the date and time the receiver was installed. Format: (CCYY-MM-DDThh:mmZ)', null=True, verbose_name='Date Installed (UTC)'),
        ),
        migrations.AlterField(
            model_name='sitereceiver',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, help_text='Enter the date and time the receiver was removed. It is important that the date removed is entered BEFORE the addition of a new receiver. Format: (CCYY-MM-DDThh:mmZ)', null=True, verbose_name='Date Removed (UTC)'),
        ),
        migrations.AlterField(
            model_name='sitesurveyedlocalties',
            name='measured',
            field=models.DateTimeField(blank=True, default=None, help_text='Enter the date of the survey local ties measurement. Format: (CCYY-MM-DDThh:mmZ)', null=True, verbose_name='Date Measured (UTC)'),
        ),
    ]
