# Generated by Django 3.2.15 on 2022-09-22 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='modified_user',
        ),
        migrations.AddField(
            model_name='agency',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
