# Generated by Django 4.1.7 on 2023-04-01 22:31

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("slm", "0002_alter_dataavailability_site"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logentry",
            name="slm_logentr_site_lo_7a2af7_idx",
        ),
        migrations.RenameField(
            model_name="logentry",
            old_name="site_log_type",
            new_name="section",
        ),
        migrations.AddField(
            model_name="logentry",
            name="file",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="slm.sitefileupload",
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="subsection",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logentries",
                to="slm.site",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="type",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Site Proposed"),
                    (2, "Add"),
                    (3, "Update"),
                    (4, "Delete"),
                    (5, "Publish"),
                    (6, "Log Upload"),
                    (7, "Image Upload"),
                    (8, "Attachment Upload"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterIndexTogether(
            name="logentry",
            index_together={
                ("site", "section"),
                ("section", "subsection"),
                ("site", "section", "subsection"),
            },
        ),
        migrations.RemoveField(
            model_name="logentry",
            name="site_log_id",
        ),
    ]
