# Generated by Django 4.1.5 on 2023-02-08 23:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0002_help_alter_siteantenna_installed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Help', 'verbose_name_plural': 'Help'},
        ),
        migrations.RenameField(
            model_name='help',
            old_name='detail',
            new_name='content',
        ),
    ]
