# Generated by Django 3.2.15 on 2022-10-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0002_auto_20221002_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='network',
            name='sites',
            field=models.ManyToManyField(related_name='networks', to='slm.Site'),
        ),
    ]
