# Generated by Django 4.1.7 on 2023-03-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0002_alter_datacenter_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datacenter',
            options={'ordering': ('name',), 'verbose_name': 'Data Center', 'verbose_name_plural': 'Data Centers'},
        ),
    ]
