# Generated by Django 4.1.6 on 2023-02-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0002_alter_siteantenna_installed_and_more'),
        ('slm', '0003_about_alter_help_options_rename_detail_help_content'),
    ]

    operations = [
    ]
