# Generated by Django 3.2.15 on 2022-10-20 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0003_auto_20221019_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataavailability',
            name='last',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='rate',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'Daily'), (1, 'Hourly'), (2, 'High Rate')], db_index=True),
        ),
        migrations.AlterField(
            model_name='dataavailability',
            name='rinex_version',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(2, 'RINEX 2'), (3, 'RINEX 3'), (4, 'RINEX 4'), (211, 'RINEX 2.11'), (300, 'RINEX 3.00'), (301, 'RINEX 3.01'), (302, 'RINEX 3.02'), (303, 'RINEX 3.03'), (304, 'RINEX 3.04'), (305, 'RINEX 3.05'), (400, 'RINEX 4.00')], db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='dataavailability',
            index_together={('site', 'rinex_version', 'rate')},
        ),
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requester', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_request', to='slm.site')),
            ],
        ),
    ]
