# Generated by Django 4.1.6 on 2023-02-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0004_merge_20230209_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Page Content: About', 'verbose_name_plural': 'Page Content: About'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Page Content: Help', 'verbose_name_plural': 'Page Content: Help'},
        ),
    ]
