# Generated by Django 3.2.15 on 2022-10-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0004_auto_20221020_0720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='silence_emails',
            field=models.BooleanField(blank=True, default=False, help_text='If set to true this user will not be sent any emails by the system. Note: this does not apply to account related emails (i.e. password resets).'),
        ),
    ]
