# Generated by Django 4.1.7 on 2023-02-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0005_alter_about_options_alter_help_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='shortname',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
