# Generated by Django 4.1.7 on 2023-04-03 18:48

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0006_alter_logentry_options_alter_logentry_index_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataavailability",
            name="rate",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(2, "Daily"), (4, "Hourly"), (8, "High Rate")],
                db_index=True,
                default=True,
                null=True,
            ),
        ),
    ]
