# Generated by Django 4.1.7 on 2023-02-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0006_alter_agency_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='public',
            field=models.BooleanField(blank=True, db_index=True, default=True, help_text='If false, this network will not appear in publicly facing data,interfaces and APIs.'),
        ),
    ]
