# Generated by Django 4.1.7 on 2023-02-25 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0007_network_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteantenna',
            name='antenna_type',
            field=models.ForeignKey(help_text='Please find your antenna radome type in https://files.igs.org/pub/station/general/rcvr_ant.tab and use the official name, taking care to get capital letters, hyphens, etc. exactly correct. The radome code from rcvr_ant.tab must be indicated in columns 17-20 of the Antenna Type, use "NONE" if no radome is installed. The antenna+radome pair must have an entry in https://files.igs.org/pub/station/general/igs05.atx with zenith- and azimuth-dependent calibration values down to the horizon. If not, notify the CB. Format: (A20, from rcvr_ant.tab; see instructions)', on_delete=django.db.models.deletion.PROTECT, related_name='site_antennas', to='slm.antenna', verbose_name='Antenna Type'),
        ),
        migrations.AlterField(
            model_name='siteantenna',
            name='radome_type',
            field=models.ForeignKey(help_text='Please find your antenna radome type in https://files.igs.org/pub/station/general/rcvr_ant.tab and use the official name, taking care to get capital letters, hyphens, etc. exactly correct. The radome code from rcvr_ant.tab must be indicated in columns 17-20 of the Antenna Type, use "NONE" if no radome is installed. The antenna+radome pair must have an entry in https://files.igs.org/pub/station/general/igs05.atx with zenith- and azimuth-dependent calibration values down to the horizon. If not, notify the CB. Format: (A20, from rcvr_ant.tab; see instructions)', on_delete=django.db.models.deletion.PROTECT, related_name='site_antennas', to='slm.radome', verbose_name='Antenna Radome Type'),
        ),
        migrations.AlterField(
            model_name='sitereceiver',
            name='receiver_type',
            field=models.ForeignKey(help_text='Please find your receiver in https://files.igs.org/pub/station/general/rcvr_ant.tab and use the official name, taking care to get capital letters, hyphens, etc. exactly correct. If you do not find a listing for your receiver, please notify the IGS Central Bureau. Format: (A20, from rcvr_ant.tab; see instructions)', on_delete=django.db.models.deletion.PROTECT, related_name='site_receivers', to='slm.receiver', verbose_name='Receiver Type'),
        ),
    ]
