# Generated by Django 4.1.7 on 2023-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0009_alter_siteantenna_radome_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteidentification',
            name='cdp_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Enter the NASA CDP identifier if available. Format: 4 character alphanumeric (A4)', max_length=50, verbose_name='CDP Number'),
        ),
        migrations.AlterField(
            model_name='siteidentification',
            name='iers_domes_number',
            field=models.CharField(db_index=True, help_text='This is strictly required. See https://itrf.ign.fr/en/network/domes/request to obtain one. Format: 9 character alphanumeric (A9)', max_length=9, verbose_name='IERS DOMES Number'),
        ),
        migrations.AlterField(
            model_name='siteindex',
            name='domes_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='sitesurveyedlocalties',
            name='cdp_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Enter the NASA CDP identifier if available. Format: (A4)', max_length=50, verbose_name='Tied Marker CDP Number'),
        ),
        migrations.AlterField(
            model_name='sitesurveyedlocalties',
            name='domes_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Enter the tied marker DOMES number if available. Format: (A9)', max_length=50, verbose_name='Tied Marker DOMES Number'),
        ),
    ]
