# Generated by Django 4.1.7 on 2023-03-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slm', '0010_alter_siteidentification_cdp_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, help_text='The time this site was first registered.', null=True),
        ),
    ]
