# Generated by Django 4.2.6 on 2023-10-13 18:09

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0014_sitelogpublished"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteantenna",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sitecollocation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sitefrequencystandard",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sitelocalepisodiceffects",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sitereceiver",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="siteantenna",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sitecollocation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sitefrequencystandard",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sitelocalepisodiceffects",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="sitereceiver",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dataavailability",
            name="rinex_version",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (2, "RINEX 2"),
                    (3, "RINEX 3"),
                    (4, "RINEX 4"),
                    (211, "RINEX 2.11"),
                    (300, "RINEX 3.00"),
                    (301, "RINEX 3.01"),
                    (302, "RINEX 3.02"),
                    (303, "RINEX 3.03"),
                    (304, "RINEX 3.04"),
                    (305, "RINEX 3.05"),
                    (400, "RINEX 4.00"),
                ],
                db_index=True,
                default=True,
                null=True,
            ),
        ),
        migrations.AlterIndexTogether(
            name="siteantenna",
            index_together={
                ("site", "subsection", "published", "installed"),
                ("subsection", "published", "installed"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitecollocation",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitefrequencystandard",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitehumiditysensor",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitelocalepisodiceffects",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitemultipathsources",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="siteotherinstrumentation",
            index_together={
                ("site", "edited", "published", "subsection"),
                ("site", "subsection", "published"),
                ("site", "edited"),
                ("subsection", "published"),
                ("site", "edited", "published"),
                ("site", "edited", "subsection"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitepressuresensor",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="siteradiointerferences",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitereceiver",
            index_together={
                ("site", "subsection", "published", "installed"),
                ("subsection", "published", "installed"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitesignalobstructions",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitesurveyedlocalties",
            index_together={
                ("site", "edited", "published", "subsection"),
                ("site", "subsection", "published"),
                ("site", "edited"),
                ("subsection", "published"),
                ("site", "edited", "published"),
                ("site", "edited", "subsection"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitetemperaturesensor",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
        migrations.AlterIndexTogether(
            name="sitewatervaporradiometer",
            index_together={
                ("subsection", "published", "effective_start"),
                ("site", "subsection", "published", "effective_start"),
            },
        ),
    ]
