# Generated by Django 4.2.11 on 2024-04-15 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0019_remove_siteantenna_marker_enu_siteantenna_marker_une_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={"ordering": ("name",)},
        ),
    ]
