# Generated by Django 4.2.11 on 2024-04-17 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0021_alter_siteform_report_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="antcal",
            new_name="slm_antcal_antenna_20827a_idx",
            old_fields=("antenna", "radome"),
        ),
        migrations.RenameIndex(
            model_name="archiveindex",
            new_name="slm_archive_begin_b89d03_idx",
            old_fields=("begin", "end"),
        ),
        migrations.RenameIndex(
            model_name="archiveindex",
            new_name="slm_archive_site_id_c1b6a6_idx",
            old_fields=("site", "begin", "end"),
        ),
        migrations.RenameIndex(
            model_name="dataavailability",
            new_name="slm_dataava_site_id_d85a77_idx",
            old_fields=("site", "rinex_version", "rate"),
        ),
        migrations.RenameIndex(
            model_name="dataavailability",
            new_name="slm_dataava_site_id_9a7916_idx",
            old_fields=("site", "rinex_version"),
        ),
        migrations.RenameIndex(
            model_name="dataavailability",
            new_name="slm_dataava_site_id_d9854f_idx",
            old_fields=("site", "rinex_version", "last"),
        ),
        migrations.RenameIndex(
            model_name="dataavailability",
            new_name="slm_dataava_site_id_60047e_idx",
            old_fields=("site", "rinex_version", "rate", "last"),
        ),
        migrations.RenameIndex(
            model_name="dataavailability",
            new_name="slm_dataava_site_id_e92b22_idx",
            old_fields=("site", "last"),
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="slm_logentr_timesta_4df389_idx",
            old_fields=("timestamp", "type", "site", "section", "subsection"),
        ),
        migrations.RenameIndex(
            model_name="siteantenna",
            new_name="slm_siteant_site_id_377271_idx",
            old_fields=("site", "subsection", "published", "installed"),
        ),
        migrations.RenameIndex(
            model_name="siteantenna",
            new_name="slm_siteant_subsect_3282cf_idx",
            old_fields=("subsection", "published", "installed"),
        ),
        migrations.RenameIndex(
            model_name="sitecollocation",
            new_name="slm_sitecol_site_id_ca071e_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitecollocation",
            new_name="slm_sitecol_subsect_b05166_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="siteform",
            new_name="slm_sitefor_edited_0821f9_idx",
            old_fields=("edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteform",
            new_name="slm_sitefor_site_id_6f8403_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteform",
            new_name="slm_sitefor_site_id_4a59c8_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitefrequencystandard",
            new_name="slm_sitefre_site_id_ce47c8_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitefrequencystandard",
            new_name="slm_sitefre_subsect_ef1188_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitehumiditysensor",
            new_name="slm_sitehum_site_id_1a719a_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitehumiditysensor",
            new_name="slm_sitehum_subsect_041d19_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="siteidentification",
            new_name="slm_siteide_edited_c1fe8b_idx",
            old_fields=("edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteidentification",
            new_name="slm_siteide_site_id_419c12_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteidentification",
            new_name="slm_siteide_site_id_6e7373_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitelocalepisodiceffects",
            new_name="slm_siteloc_site_id_65b5eb_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitelocalepisodiceffects",
            new_name="slm_siteloc_subsect_4942ad_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitelocation",
            new_name="slm_siteloc_edited_722b13_idx",
            old_fields=("edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitelocation",
            new_name="slm_siteloc_site_id_1f1467_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitelocation",
            new_name="slm_siteloc_site_id_f1eb5f_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitemoreinformation",
            new_name="slm_sitemor_edited_5fc904_idx",
            old_fields=("edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitemoreinformation",
            new_name="slm_sitemor_site_id_773a37_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitemoreinformation",
            new_name="slm_sitemor_site_id_47b2d7_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitemultipathsources",
            new_name="slm_sitemul_site_id_6a199b_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitemultipathsources",
            new_name="slm_sitemul_subsect_b9fa3d_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_site_id_3f3f4d_idx",
            old_fields=("site", "subsection", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_site_id_0a11e1_idx",
            old_fields=("site", "edited", "published", "subsection"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_site_id_2f264f_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_subsect_08a59a_idx",
            old_fields=("subsection", "published"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_site_id_8dcff0_idx",
            old_fields=("site", "edited", "subsection"),
        ),
        migrations.RenameIndex(
            model_name="siteotherinstrumentation",
            new_name="slm_siteoth_site_id_7b7929_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitepressuresensor",
            new_name="slm_sitepre_site_id_568a2d_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitepressuresensor",
            new_name="slm_sitepre_subsect_8383b8_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="siteradiointerferences",
            new_name="slm_siterad_site_id_d6634e_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="siteradiointerferences",
            new_name="slm_siterad_subsect_e0667b_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitereceiver",
            new_name="slm_siterec_site_id_05c5f5_idx",
            old_fields=("site", "subsection", "published", "installed"),
        ),
        migrations.RenameIndex(
            model_name="sitereceiver",
            new_name="slm_siterec_subsect_a618d0_idx",
            old_fields=("subsection", "published", "installed"),
        ),
        migrations.RenameIndex(
            model_name="sitesignalobstructions",
            new_name="slm_sitesig_site_id_d888b6_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitesignalobstructions",
            new_name="slm_sitesig_subsect_a977a3_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_site_id_9b2439_idx",
            old_fields=("site", "subsection", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_site_id_988dda_idx",
            old_fields=("site", "edited", "published", "subsection"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_site_id_4e9caa_idx",
            old_fields=("site", "edited", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_subsect_471fcf_idx",
            old_fields=("subsection", "published"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_site_id_3d7dcb_idx",
            old_fields=("site", "edited", "subsection"),
        ),
        migrations.RenameIndex(
            model_name="sitesurveyedlocalties",
            new_name="slm_sitesur_site_id_742f94_idx",
            old_fields=("site", "edited"),
        ),
        migrations.RenameIndex(
            model_name="sitetemperaturesensor",
            new_name="slm_sitetem_site_id_e3e602_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitetemperaturesensor",
            new_name="slm_sitetem_subsect_9160c5_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitewatervaporradiometer",
            new_name="slm_sitewat_site_id_3bfa3f_idx",
            old_fields=("site", "subsection", "published", "effective_start"),
        ),
        migrations.RenameIndex(
            model_name="sitewatervaporradiometer",
            new_name="slm_sitewat_subsect_8ccea2_idx",
            old_fields=("subsection", "published", "effective_start"),
        ),
    ]
