# Generated by Django 4.2.13 on 2024-06-10 22:04

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0024_alter_agency_name_alter_agency_shortname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsitelog",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "Legacy 9-Char (ASCII)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geodesymlinvalid",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "Legacy 9-Char (ASCII)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitefileupload",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "Legacy 9-Char (ASCII)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
    ]
