# Generated by Django 4.2.13 on 2024-07-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0027_importalert_file_contents_importalert_findings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antenna",
            name="replaced",
            field=models.ManyToManyField(
                help_text="The old codings for this antenna if any exist.",
                related_name="replaced_by",
                to="slm.antenna",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="url",
            field=models.URLField(
                default=None, help_text="The manufacturer's website.", null=True
            ),
        ),
        migrations.AddField(
            model_name="radome",
            name="replaced",
            field=models.ManyToManyField(
                help_text="The old codings for this radome if any exist.",
                related_name="replaced_by",
                to="slm.radome",
            ),
        ),
        migrations.AddField(
            model_name="receiver",
            name="replaced",
            field=models.ManyToManyField(
                help_text="The old codings for this receiver if any exist.",
                related_name="replaced_by",
                to="slm.receiver",
            ),
        ),
    ]
