[project]
name = "{{ package_name }}"
version = "0.1.0"
description = ""
requires-python = ">=3.8,<4.0"
authors = []
dependencies = [
    "igs-slm>={{ slm_version }},<{{ slm_version_next_major }}",
]

[tool.uv]
package = true

{% if local_slm %}
[tool.uv.sources]
igs-slm = { path = "{{ local_slm }}", editable = true }
{% endif %}


[project.scripts]
{{ site }} = "sites.{{ site }}.manage:main"

[tool.hatch.build.targets.wheel]
packages = [
    "src/sites",
    "src/{{ extension_app }}"
]
{% if local_slm %}
[tool.hatch.metadata]
allow-direct-references = true
{% endif %}

[dependency-groups]
dev = [
    "django-extensions>=3.0,<5.0",
    "django-debug-toolbar>=4.4.6",
    "ipython==8.12.3",
    "ipdb>=0.13.13,<1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

