# Generated by Django 4.2.20 on 2025-05-09 21:04

import django.contrib.postgres.constraints
import django.db.models.constraints
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "verify_index"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="archiveindex",
            name="no_overlapping_ranges_per_site",
        ),
        migrations.AddConstraint(
            model_name="archiveindex",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                expressions=[("site", "="), ("valid_range", "&&")],
                name="no_overlapping_ranges_per_site",
            ),
        ),
    ]
