# Generated by Django 4.2.23 on 2025-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "simplify_daily_index_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsitelog",
            name="size",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="geodesymlinvalid",
            name="size",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitefileupload",
            name="size",
            field=models.PositiveIntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sitemoreinformation",
            name="more_info",
            field=models.URLField(
                blank=True,
                db_index=True,
                default="",
                max_length=8000,
                verbose_name="URL for More Information",
            ),
        ),
    ]
