# Generated by Django 4.2.20 on 2025-06-27 20:37

from django.db import migrations, models

import slm.models.system


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0001_remove_archiveindex_no_overlapping_ranges_per_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsitelog",
            name="file",
            field=models.FileField(
                help_text="A pointer to the uploaded file on disk.",
                max_length=255,
                unique=True,
                upload_to=slm.models.system.site_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="geodesymlinvalid",
            name="file",
            field=models.FileField(
                help_text="A pointer to the uploaded file on disk.",
                max_length=255,
                unique=True,
                upload_to=slm.models.system.site_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="sitefileupload",
            name="file",
            field=models.FileField(
                help_text="A pointer to the uploaded file on disk.",
                max_length=255,
                unique=True,
                upload_to=slm.models.system.site_upload_path,
            ),
        ),
    ]
