# Generated by Django 4.2.20 on 2025-06-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0002_alter_archivedsitelog_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsitelog",
            name="name",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="archivedsitelog",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When the file was created or uploaded.",
            ),
        ),
        migrations.AlterField(
            model_name="sitefileupload",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="When the file was created or uploaded.",
            ),
        ),
    ]
