# Generated by Django 4.2.20 on 2025-07-08 19:42

from django.db import migrations

import slm.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0003_alter_archivedsitelog_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="name",
            field=slm.models.fields.StationNameField(
                db_index=True,
                help_text="The name of the station.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
