# Generated by Django 4.2.20 on 2025-07-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0004_alter_site_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SLMVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_str", models.CharField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
