# Generated by Django 4.1.7 on 2023-04-02 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("slm", "0004_alter_logentry_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
            },
        ),
        migrations.AlterField(
            model_name="logentry",
            name="section",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_history",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="site",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edit_history",
                to="slm.site",
            ),
        ),
    ]
