# Generated by Django 4.1.7 on 2023-04-02 01:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0005_alter_logentry_options_alter_logentry_section_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logentry",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Log Entry",
                "verbose_name_plural": "Log Entries",
            },
        ),
        migrations.AlterIndexTogether(
            name="logentry",
            index_together=set(),
        ),
    ]
