# Generated by Django 4.1.8 on 2023-04-21 16:57

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0010_alter_dataavailability_rinex_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteidentification",
            name="fracture_spacing",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("0", "0 cm"),
                    ("1", "1-10 cm"),
                    ("11", "11-50 cm"),
                    ("51", "51-200 cm"),
                    ("200", "over 200 cm"),
                ],
                db_index=True,
                default=None,
                help_text="If known, describe the fracture spacing of the bedrock. Format: (1-10 cm/11-50 cm/51-200 cm/over 200 cm)",
                max_length=50,
                null=True,
                verbose_name="Fracture Spacing",
            ),
        ),
    ]
