# Generated by Django 4.2.11 on 2024-04-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0020_alter_manufacturer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteform",
            name="report_type",
            field=models.CharField(
                blank=True,
                default="NEW",
                help_text="Enter type of report. Example: (UPDATE).",
                max_length=50,
                verbose_name="Report Type",
            ),
        ),
    ]
