# Generated by Django 4.2.13 on 2024-06-12 19:28

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0025_alter_archivedsitelog_log_format_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsitelog",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "ASCII (9-Char)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="geodesymlinvalid",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "ASCII (9-Char)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sitefileupload",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "ASCII (9-Char)"),
                ],
                db_index=True,
                default=None,
                help_text="The site log format. (Only if file_type is Site Log)",
                null=True,
            ),
        ),
    ]
