# Generated by Django 4.2.13 on 2024-07-10 00:03

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0026_alter_archivedsitelog_log_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importalert",
            name="file_contents",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The text contents of the file that import was attempted from (if applicable).",
            ),
        ),
        migrations.AddField(
            model_name="importalert",
            name="findings",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="importalert",
            name="log_format",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[
                    (1, "Legacy (ASCII)"),
                    (2, "GeodesyML"),
                    (3, "JSON"),
                    (4, "ASCII (9-Char)"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
