# Generated by Django 4.2.13 on 2024-07-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0028_antenna_replaced_manufacturer_url_radome_replaced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
