# Generated by Django 4.2.13 on 2024-07-12 20:16

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0029_manufacturer_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antenna",
            name="state",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(100, "In Use"), (101, "Retired"), (102, "Unverified")],
                db_index=True,
                default=102,
                help_text="Has this equipment been verified and is it in active production?",
            ),
        ),
        migrations.AlterField(
            model_name="radome",
            name="state",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(100, "In Use"), (101, "Retired"), (102, "Unverified")],
                db_index=True,
                default=102,
                help_text="Has this equipment been verified and is it in active production?",
            ),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="state",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                choices=[(100, "In Use"), (101, "Retired"), (102, "Unverified")],
                db_index=True,
                default=102,
                help_text="Has this equipment been verified and is it in active production?",
            ),
        ),
    ]
