# Generated by Django 4.2.14 on 2024-11-13 23:19

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slm", "0030_alter_antenna_state_alter_radome_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antenna",
            name="features",
            field=django_enum.fields.EnumPositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "(MMI) Man-Machine Interface"),
                    (2, "(NOM) North Orientation Mark"),
                    (3, "(RXC) Receiver Connector"),
                    (4, "(BAT) Battery Compartment Door Release"),
                    (5, "(BTD) Bottom of Tear Drop Shape"),
                    (6, "(CMP) Mounted Compass"),
                    (7, "(DIS) Display/Digital Readout"),
                    (8, "(DRY) Cap or Cover for Drying Agent"),
                    (9, "(PCS) PC Card Slot"),
                    (10, "(TMT) Tape Measure Tab or Notch for Slant Height Pole"),
                    (11, "(CAC) Nonspecific Cable Connector"),
                    (12, "(CTC) External Controller Connector"),
                    (13, "(DAC) Data Cable Connector"),
                    (14, "(PWC) Power Port"),
                    (15, "(RTC) RTK Connector"),
                    (16, "(UNK) Unknown"),
                    (17, "(OMM) Opposite of Man-Machine Interface"),
                ],
                db_index=True,
                default=None,
                help_text='NOM/RXC/XXX from "antenna.gra"; see NRP abbreviations.',
                null=True,
                verbose_name="Antenna Features",
            ),
        ),
    ]
