name: security

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Set to on, to open ssh debug session.'
        required: true
        default: 'off'
  schedule:
    - cron: '0 13 * * *'  # Runs at 6 am pacific every day

jobs:

  security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - name: Setup tmate session
        if: ${{ github.event.inputs.debug == 'on' }}
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        timeout-minutes: 60
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Refresh Requirements
        run: |
          poetry run pip install poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev
      - uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
